"""Make DB ready to store knowledgebase

Revision ID: 12a4dfbdc7e3
Revises: bbd137f0d39e
Create Date: 2026-06-11 14:37:30.812422

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from pgvector.sqlalchemy import Vector


# revision identifiers, used by Alembic.
revision: str = '12a4dfbdc7e3'
down_revision: Union[str, Sequence[str], None] = 'bbd137f0d39e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('knowledge_base_chunks',
    sa.Column('chunk_text', sa.Text(), nullable=False),
    sa.Column('url', sa.String(length=2048), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_base_chunks_id'), 'knowledge_base_chunks', ['id'], unique=False)
    op.create_index(op.f('ix_knowledge_base_chunks_url'), 'knowledge_base_chunks', ['url'], unique=False)
    op.create_table('knowledge_base_embeddings',
    sa.Column('chunk_id', sa.Integer(), nullable=False),
    sa.Column('embedding', Vector(3072), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['chunk_id'], ['knowledge_base_chunks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_base_embeddings_chunk_id'), 'knowledge_base_embeddings', ['chunk_id'], unique=True)
    op.create_index(op.f('ix_knowledge_base_embeddings_id'), 'knowledge_base_embeddings', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_knowledge_base_embeddings_id'), table_name='knowledge_base_embeddings')
    op.drop_index(op.f('ix_knowledge_base_embeddings_chunk_id'), table_name='knowledge_base_embeddings')
    op.drop_table('knowledge_base_embeddings')
    op.drop_index(op.f('ix_knowledge_base_chunks_url'), table_name='knowledge_base_chunks')
    op.drop_index(op.f('ix_knowledge_base_chunks_id'), table_name='knowledge_base_chunks')
    op.drop_table('knowledge_base_chunks')
    # ### end Alembic commands ###
