services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - api
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    env_file:
      - ./secrets/api/.env
    ports:
      - "8000:8000"
    volumes:
      - ./api:/app
    depends_on:
      - db
    command: >
      uvicorn app.main:app
      --host 0.0.0.0
      --port 8000
      --reload

  db:
    image: pgvector/pgvector:pg16
    env_file:
      - ./secrets/db/.env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  scraper:
    build:
      context: ./scraper
      dockerfile: Dockerfile
    volumes:
      - ./scraper:/app
    env_file:
      - ./secrets/scraper/.env
    depends_on:
      - api
    command: tail -f /dev/null

volumes:
  postgres_data:
